/** Standard JSON-RPC codes plus the Helve range — `docs/tool-protocol.md` §2. */
export const HelveErrorCode = {
  ParseError: -32700,
  InvalidRequest: -32600,
  MethodNotFound: -32601,
  InvalidParams: -32602,
  InternalError: -32603,
  /** Tool process exited or crashed — generated by the host. */
  ProcessExited: -32000,
  /** Request timed out — generated by the host, or by this bridge locally. */
  Timeout: -32001,
  /** Handshake failed — generated by the host. */
  HandshakeFailed: -32002,
} as const;

/**
 * Every rejection `invoke` can produce, from either host, normalizes to
 * this — a `{code, message, data}` error envelope and a local timeout look
 * the same to calling code, which is the point: tool UI shouldn't need to
 * know which host it's running under to handle a failure.
 */
export class HelveRpcError extends Error {
  readonly code: number;
  readonly data?: unknown;

  constructor(code: number, message: string, data?: unknown) {
    super(message);
    this.name = "HelveRpcError";
    this.code = code;
    this.data = data;
  }
}
